#
#   InflectionFeatureOperations.pyi
#
#   Type stubs for InflectionFeatureOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations

class InflectionFeatureOperations(BaseOperations[Any]):
    """InflectionFeatureOperations operations"""

    def GetAll(self, *args: Any, **kwargs: Any) -> Iterator[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, obj: Any, deep: bool = True) -> Any: ...

    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    
    def __getattr__(self, name: str) -> Any: ...
