#
#   POSOperations.pyi
#
#   Type stubs for POSOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations

class POSOperations(BaseOperations[Any]):
    """Parts of Speech operations"""

    def GetAll(self, *args: Any, **kwargs: Any) -> Iterator[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, *args: Any, **kwargs: Any) -> None: ...
    def Duplicate(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetName(self, pos: Any) -> Optional[str]: ...
    def SetName(self, pos: Any, name: str) -> None: ...
    def GetAbbreviation(self, pos: Any) -> Optional[str]: ...
    def SetAbbreviation(self, pos: Any, abbr: str) -> None: ...
    def GetDescription(self, pos: Any) -> Optional[str]: ...
    def SetDescription(self, pos: Any, desc: str) -> None: ...
    def GetGUID(self, pos: Any) -> Optional[str]: ...
    def GetParent(self, pos: Any) -> Optional[Any]: ...
    def GetSubPOS(self, pos: Any) -> Iterator[Any]: ...
    def CreateSubPOS(self, parent: Any, name: str, abbr: str = "") -> Any: ...
