#
#   LexEntryOperations.pyi
#
#   Type stubs for LexEntryOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations

class LexEntryOperations(BaseOperations[Any]):
    """Lexical Entry operations"""

    def GetAll(self) -> Iterator[Any]: ...
    def Find(self, headword: str) -> Optional[Any]: ...
    def Exists(self, headword: str) -> bool: ...
    def Create(self, headword: str, morphType: str = "stem") -> Any: ...
    def Delete(self, entry: Any) -> None: ...
    def Duplicate(self, entry: Any, deep: bool = True) -> Any: ...

    def GetName(self, entry: Any) -> Optional[str]: ...
    def SetName(self, entry: Any, name: str) -> None: ...
    def GetHeadword(self, entry: Any) -> Optional[str]: ...
    def SetHeadword(self, entry: Any, headword: str) -> None: ...
    def GetGUID(self, entry: Any) -> Optional[str]: ...

    def GetSenses(self, entry: Any) -> Iterator[Any]: ...
    def AddSense(self, entry: Any, gloss: str = "", languageCode: str = "en") -> Any: ...
    def GetAllomorphs(self, entry: Any) -> Iterator[Any]: ...
    def AddAllomorph(self, entry: Any, form: str) -> Any: ...
    def GetVariants(self, entry: Any) -> Iterator[Any]: ...
    def AddVariant(self, entry: Any, form: str) -> Any: ...
