#
#   LexEntryOperations.pyi
#
#   Type stubs for LexEntryOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations

class LexEntryOperations(BaseOperations[Any]):
    """Lexical Entry operations"""

    def GetAll(self, *args: Any, **kwargs: Any) -> Iterator[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, *args: Any, **kwargs: Any) -> None: ...
    def Duplicate(self, *args: Any, **kwargs: Any) -> Any: ...

    def GetName(self, entry: Any) -> Optional[str]: ...
    def SetName(self, entry: Any, name: str) -> None: ...
    def GetHeadword(self, entry: Any) -> Optional[str]: ...
    def SetHeadword(self, entry: Any, headword: str) -> None: ...
    def GetGUID(self, entry: Any) -> Optional[str]: ...

    def GetSenses(self, entry: Any) -> Iterator[Any]: ...
    def AddSense(self, entry: Any, gloss: str = "", languageCode: str = "en") -> Any: ...
    def GetAllomorphs(self, entry: Any) -> Iterator[Any]: ...
    def AddAllomorph(self, entry: Any, form: str) -> Any: ...
    def GetVariants(self, entry: Any) -> Iterator[Any]: ...
    def AddVariant(self, entry: Any, form: str) -> Any: ...
