#
#   LexSenseOperations.pyi
#
#   Type stubs for LexSenseOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations

class LexSenseOperations(BaseOperations[Any]):
    """Lexical Sense operations"""

    def GetAll(self, *args: Any, **kwargs: Any) -> Iterator[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, *args: Any, **kwargs: Any) -> None: ...
    def Duplicate(self, *args: Any, **kwargs: Any) -> Any: ...

    def GetName(self, sense: Any) -> Optional[str]: ...
    def SetName(self, sense: Any, name: str) -> None: ...
    def GetGloss(self, sense: Any, languageCode: str = "en") -> Optional[str]: ...
    def SetGloss(self, sense: Any, gloss: str, languageCode: str = "en") -> None: ...
    def GetDefinition(self, sense: Any, languageCode: str = "en") -> Optional[str]: ...
    def SetDefinition(self, sense: Any, definition: str, languageCode: str = "en") -> None: ...
    def GetGUID(self, sense: Any) -> Optional[str]: ...

    def GetExamples(self, sense: Any) -> Iterator[Any]: ...
    def AddExample(self, sense: Any, example: str) -> Any: ...
    def GetSubsenses(self, sense: Any) -> Iterator[Any]: ...
    def AddSubsense(self, sense: Any, gloss: str = "") -> Any: ...
