#
#   BaseOperations.pyi
#
#   Type stubs for BaseOperations
#   Base class for all Operations classes
#

from typing import Any, Optional, Iterator, List, Union, Generic, TypeVar

T = TypeVar('T')

class BaseOperations(Generic[T]):
    """Base class for all FLEx Operations"""

    project: Any

    def __init__(self, project: Any) -> None: ...

    # Common CRUD methods (flexible signatures to accommodate various Operations classes)
    def GetAll(self, *args: Any, **kwargs: Any) -> Iterator[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...  # Signature varies by Operations class
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, obj: Any, deep: bool = True) -> Any: ...

    # Common property methods
    def GetName(self, obj: T) -> Optional[str]: ...
    def SetName(self, obj: T, name: str) -> None: ...
    def GetAbbreviation(self, obj: T) -> Optional[str]: ...
    def SetAbbreviation(self, obj: T, abbr: str) -> None: ...
    def GetDescription(self, obj: T) -> Optional[str]: ...
    def SetDescription(self, obj: T, desc: str) -> None: ...
    def GetGUID(self, obj: T) -> Optional[str]: ...

    # Type checking
    def __getattr__(self, name: str) -> Any: ...
